name: Auto Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22

          script: |
            echo "🚀 STARTING DEPLOYMENT..."

            # =========================
            # MASUK KE PROJECT
            # =========================
            cd /var/www/Notes-App-23A5 || exit

            echo "📥 PULL LATEST CODE..."
            git pull origin main

            # =========================
            # BACKEND
            # =========================
            echo "📦 INSTALL BACKEND..."
            cd backend || exit

            npm ci

            echo "♻️ RESTART BACKEND..."
            pm2 restart notes-api || pm2 start index.js --name notes-api

            pm2 save

            # =========================
            # FRONTEND
            # =========================
            echo "🎨 BUILD FRONTEND..."
            cd ../frontend || exit

            npm ci

            npm run build

            # =========================
            # NGINX
            # =========================
            echo "🔁 RESTART NGINX..."
            sudo systemctl restart nginx

            echo "✅ DEPLOY SUCCESS!"
